# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0002_auto_20180126_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lot_num', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('container', models.CharField(max_length=100)),
                ('net_quantity', models.IntegerField()),
                ('pnet_quantity', models.IntegerField()),
                ('tquantity', models.IntegerField()),
                ('mfg_date', models.DateTimeField()),
                ('action', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
