# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0004_auto_20180126_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='tquantity',
            field=models.FloatField(),
        ),
    ]
