# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0010_auto_20180130_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='pnet_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
