# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0011_auto_20180209_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='mfg_date',
            field=models.DateField(),
        ),
    ]
