# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0012_auto_20180209_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='mfg_date',
            field=models.DateField(default=None),
        ),
    ]
