# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0015_auto_20180313_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actioner', models.CharField(max_length=225)),
                ('container', models.CharField(max_length=100)),
                ('net_quantity', models.IntegerField()),
                ('pnet_quantity', models.FloatField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='action',
        ),
        migrations.AddField(
            model_name='history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='log_reg.Inventory'),
        ),
    ]
