# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0016_auto_20180313_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='tquantity',
            field=models.FloatField(default=0),
        ),
    ]
