# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0017_history_tquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='document',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(),
        ),
    ]
