# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0019_auto_20180329_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='document',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d'),
        ),
    ]
