# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-30 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0020_auto_20180329_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='actioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to=settings.AUTH_USER_MODEL),
        ),
    ]
